"""initial migration 3

Revision ID: 0986e33a27c8
Revises: e82cea506286
Create Date: 2025-08-05 13:35:15.991334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0986e33a27c8'
down_revision: Union[str, Sequence[str], None] = 'e82cea506286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('publish', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'publish')
    # ### end Alembic commands ###
